Repository jenkinsci/jenkins-test-harness, pull requests merged in 2019-06, with the labels that each got.

#130 Add Hamcrest matchers for Secret and Pattern
  src/main/java/org/jvnet/hudson/test/JenkinsMatchers.java
  src/test/java/org/jvnet/hudson/test/JenkinsMatchersTest.java
Labels: enhancement

#136 Enable Release Drafter for Jenkins Test Harness
  .github/release-drafter.yml
Labels: internal

#132 Allow port reuse in RestartableJenkinsRule
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
  src/main/java/org/jvnet/hudson/test/RestartableJenkinsRule.java
  src/test/java/org/jvnet/hudson/test/RestartableJenkinsRuleTest.java
Labels: enhancement

#135 [JENKINS-57653] Introduce JMH benchmarks to Jenkins Test Harness
  docs/jmh-benchmarks.adoc
  pom.xml
  src/main/java/jenkins/benchmark/jmh/BenchmarkFinder.java
  src/main/java/jenkins/benchmark/jmh/JmhBenchmark.java
  src/main/java/jenkins/benchmark/jmh/JmhBenchmarkState.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
  src/test/java/jenkins/benchmark/jmh/BenchmarkTest.java
  src/test/java/jenkins/benchmark/jmh/samples/JmhStateBenchmark.java
Labels: enhancement

#139 Deleting MilliSecLogFormatter
  src/main/java/org/jvnet/hudson/test/MilliSecLogFormatter.java
Labels: removed

#137 Switch code annotations to the SpotBugs library
  pom.xml
Labels: internal

#138 Avoid printing duplicated messages when LoggerRule is used
  src/main/java/org/jvnet/hudson/test/LoggerRule.java
Labels: bug

#140 Update `@since TODO` for benchmark classes in JavaDocs
  src/main/java/jenkins/benchmark/jmh/BenchmarkFinder.java
  src/main/java/jenkins/benchmark/jmh/JmhBenchmark.java
  src/main/java/jenkins/benchmark/jmh/JmhBenchmarkState.java
  src/main/java/org/jvnet/hudson/test/JenkinsMatchers.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: documentation

#143 Move changelogs to GitHub releases
  README.md
Labels: documentation
