Repository jenkinsci/jenkins-test-harness, pull requests merged in 2019-12, with the labels that each got.

#171 Upgrade htmlunit to 2.36.0
  pom.xml
  src/main/java/com/gargoylesoftware/htmlunit/WebClientUtil.java
  src/main/java/com/gargoylesoftware/htmlunit/html/DomNodeUtil.java
Labels: breaking, dependencies

#174 Add implementation for getAffectedFiles to FakeChangeLogSCM#EntryImpl
  src/main/java/org/jvnet/hudson/test/FakeChangeLogSCM.java
Labels: enhancement

#186 Update Java Microbenchmark Harness to 1.22, use a single property to manage dependencies
  pom.xml
Labels: dependencies

#185 workaround JENKINS-60308 by not wrapping the IOException
  src/main/java/org/jvnet/hudson/test/TemporaryDirectoryAllocator.java
Labels: bug

#187 [JENKINS-55381] Add test for TestCrumbIssuer compatibility with JCasC
  pom.xml
  src/test/java/org/jvnet/hudson/test/TestCrumbIssuerConfigurationAsCodeTest.java
Labels: internal

#189 Fix typo in test name
  src/test/java/org/jvnet/hudson/test/TestCrumbIssuerConfigurationAsCodeTest.java
Labels: bug
