Repository jenkinsci/jenkins-test-harness, pull requests merged in 2019-10, with the labels that each got.

#163 Adding LICENSE file to the project
  LICENSE
Labels: documentation

#161 Bump hamcrest-library from 1.3 to 2.1
  pom.xml
Labels: dependencies

#166 Stop swallowing exceptions that happen in `TestEnvironment#dispose()`
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: bug

#170 Add FunctionalInterface annotation to RestartableJenkinsRule.Step
  src/main/java/org/jvnet/hudson/test/RestartableJenkinsRule.java
Labels: enhancement, hacktoberfest

#167 Introduce new `JenkinsRule#buildAndAssertStatus()` method
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: enhancement

#169 Update org-netbeans-insane from RELEASE802 to RELEASE111
  pom.xml
Labels: dependencies
