Repository jenkinsci/jenkins-test-harness, pull requests merged in 2020-10, with the labels that each got.

#244 Deprecate RestartableJenkinsRule.addStep* and update Javadoc
  src/main/java/org/jvnet/hudson/test/RestartableJenkinsRule.java
Labels: documentation

#242 Added FlagRule
  src/main/java/org/jvnet/hudson/test/FlagRule.java
  src/main/java/org/jvnet/hudson/test/TemporaryDirectoryAllocator.java
  src/test/java/org/jvnet/hudson/test/FlagRuleNoReplacementTest.java
  src/test/java/org/jvnet/hudson/test/FlagRuleReplacementTest.java
  src/test/java/org/jvnet/hudson/test/FlagRuleSystemPropertyTest.java
Labels: enhancement

#246 [Hacktoberfest] Code cleanup
  src/main/java/com/gargoylesoftware/htmlunit/WebResponseListener.java
  src/main/java/com/gargoylesoftware/htmlunit/html/HtmlElementUtil.java
  src/main/java/com/gargoylesoftware/htmlunit/html/HtmlFormUtil.java
  src/main/java/hudson/security/pages/SignupPage.java
  src/main/java/hudson/slaves/DummyCloudImpl.java
  src/main/java/org/jvnet/hudson/test/BuildWatcher.java
  src/main/java/org/jvnet/hudson/test/ChannelShutdownListener.java
  src/main/java/org/jvnet/hudson/test/ClosureExecuterAction.java
  src/main/java/org/jvnet/hudson/test/DefaultConstructorChecker.java
  src/main/java/org/jvnet/hudson/test/ExtractChangeLogParser.java
  src/main/java/org/jvnet/hudson/test/ExtractResourceSCM.java
  src/main/java/org/jvnet/hudson/test/FakeChangeLogSCM.java
  src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
  src/main/java/org/jvnet/hudson/test/JellyTestSuiteBuilder.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
  src/main/java/org/jvnet/hudson/test/LoggerRule.java
  src/main/java/org/jvnet/hudson/test/MemoryAssert.java
  src/main/java/org/jvnet/hudson/test/MockAuthorizationStrategy.java
  src/main/java/org/jvnet/hudson/test/MockFolder.java
  src/main/java/org/jvnet/hudson/test/RestartableJenkinsRule.java
  src/main/java/org/jvnet/hudson/test/RunLoadCounter.java
  src/main/java/org/jvnet/hudson/test/SecuredMockFolder.java
  src/main/java/org/jvnet/hudson/test/TemporaryDirectoryAllocator.java
  src/main/java/org/jvnet/hudson/test/UnitTestSupportingPluginManager.java
  src/main/java/org/jvnet/hudson/test/rhino/CallStackFrame.java
  src/main/java/org/jvnet/hudson/test/rhino/JavaScriptDebugger.java
  src/test/java/org/jvnet/hudson/main/JenkinsRuleTimeoutTest.java
  src/test/java/org/jvnet/hudson/test/JenkinsMatchersTest.java
  src/test/java/org/jvnet/hudson/test/JenkinsRuleTest.java
  src/test/java/org/jvnet/hudson/test/LoggerRuleTest.java
  src/test/java/org/jvnet/hudson/test/MockAuthorizationStrategyTest.java
  src/test/java/org/jvnet/hudson/test/RestartableJenkinsRuleTest.java
  src/test/java/org/jvnet/hudson/test/TestCrumbIssuerConfigurationAsCodeTest.java
  src/test/java/org/jvnet/hudson/test/TestExtensionTest.java
  src/test/java/org/jvnet/hudson/test/recipes/LocalDataZipTest.java
Labels: hacktoberfest-accepted, internal

#258 yeet JCasC out of JTH
  pom.xml
  src/test/java/org/jvnet/hudson/test/TestCrumbIssuerConfigurationAsCodeTest.java
Labels: tests

#252 Code cleanup
  src/main/java/com/gargoylesoftware/htmlunit/WebResponseListener.java
  src/main/java/com/gargoylesoftware/htmlunit/html/DomNodeUtil.java
  src/main/java/hudson/security/pages/SignupPage.java
  src/main/java/org/jvnet/hudson/test/DefaultConstructorChecker.java
  src/main/java/org/jvnet/hudson/test/GroovyHudsonTestCase.java
  src/main/java/org/jvnet/hudson/test/GroovyJenkinsRule.java
  src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
  src/test/java/org/jvnet/hudson/test/FlagRuleNoReplacementTest.java
  src/test/java/org/jvnet/hudson/test/FlagRuleReplacementTest.java
  src/test/java/org/jvnet/hudson/test/MockAuthorizationStrategyTest.java
  src/test/java/org/jvnet/hudson/test/recipes/LocalDataTest.java
Labels: chore

#260 Improved Javadoc for WithPlugin
  src/main/java/org/jvnet/hudson/test/recipes/WithPlugin.java
Labels: documentation
