Repository jenkinsci/jenkins-test-harness, pull requests merged in 2020-04, with the labels that each got.

#205 Add support for customization on the server
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: enhancement

#210 waitForCompletion should wait for !Run.logUpdated even after !Run.building
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: bug

#209 Add WithTimeout support for JUnit4
  src/main/java/org/jvnet/hudson/test/recipes/WithTimeout.java
Labels: enhancement

#207 Make this compile again with a Jenkins 2.61+ dependency
  pom.xml
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: internal

#206 JenkinsRule.waitOnline should stream Computer.logText
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: enhancement

#216 add some javadoc for disabling plugins
  src/main/java/org/jvnet/hudson/test/RestartableJenkinsRule.java
  src/main/java/org/jvnet/hudson/test/TestPluginManager.java
Labels: documentation
