Repository jenkinsci/jenkins-test-harness, pull requests merged in 2020-01, with the labels that each got.

#183 [JEP-222] - Add WebSocket support when running Jenkins test rules
  pom.xml
Labels: enhancement

#193 [JENKINS-60694] Do not use defaults for acceptors & selectors
  src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
  src/main/java/org/jvnet/hudson/test/JavaNetReverseProxy.java
Labels: bug

#194 [JENKINS-58771] Warn if ChannelShutdownListener loaded outside of a test context
  src/main/java/org/jvnet/hudson/test/ChannelShutdownListener.java
Labels: bug

#197 [JENKINS-60821] let Jetty configure its own defaults
  src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
  src/main/java/org/jvnet/hudson/test/JavaNetReverseProxy.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: bug

#191 Add the GitHub repo URLs to the Maven metadata
  pom.xml
Labels: internal
