Repository jenkinsci/jenkins-test-harness, pull requests merged in 2021-12, with the labels that each got.

#352 Allowing `RealJenkinsRule` to use `@LocalData`
  src/main/java/org/jvnet/hudson/test/HudsonHomeLoader.java
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
  src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
  src/test/resources/org/jvnet/hudson/test/RealJenkinsRuleTest/localData/jobs/x/config.xml
Labels: enhancement

#353 Add new JenkinsSessionRule.getHome method
  src/main/java/org/jvnet/hudson/test/JenkinsSessionRule.java
Labels: enhancement

#356 Update parent POM
  pom.xml
Labels: dependencies

#357 GC before trying to delete the Jenkins home directory
  src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: bug

#362 Bump `support-log-formatter` from 1.0 to 1.1
  pom.xml
Labels: dependencies, java

#368 Use `{@code}` rather than `<tt>`
  src/main/java/com/gargoylesoftware/htmlunit/html/DomNodeUtil.java
  src/main/java/org/jvnet/hudson/test/HudsonHomeLoader.java
  src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
  src/main/java/org/jvnet/hudson/test/WarExploder.java
  src/main/java/org/jvnet/hudson/test/recipes/LocalData.java
Labels: documentation

#373 Adopt POM Code Convention
  pom.xml
Labels: internal

#374 Sort dependencies
  pom.xml
Labels: internal
