Repository jenkinsci/jenkins-test-harness, pull requests merged in 2021-05, with the labels that each got.

#308 `JenkinsRuleTimeoutTest` was flaky
  pom.xml
  src/test/java/org/jvnet/hudson/main/JenkinsRuleTimeout1Test.java
  src/test/java/org/jvnet/hudson/main/JenkinsRuleTimeout2Test.java
  src/test/java/org/jvnet/hudson/main/JenkinsRuleTimeout3Test.java
  src/test/java/org/jvnet/hudson/main/JenkinsRuleTimeout4Test.java
  src/test/java/org/jvnet/hudson/main/JenkinsRuleTimeout5Test.java
  src/test/java/org/jvnet/hudson/main/JenkinsRuleTimeout6Test.java
  src/test/java/org/jvnet/hudson/main/JenkinsRuleTimeout7Test.java
  src/test/java/org/jvnet/hudson/main/JenkinsRuleTimeoutTestBase.java
Labels: tests

#304 Ensure proper stream cleanup
  src/main/java/org/jvnet/hudson/test/ExtractChangeLogParser.java
Labels: chore

#303 [JENKINS-48466] JenkinsRule support for JUnit 5
  pom.xml
  src/main/java/org/jvnet/hudson/test/junit/jupiter/JenkinsRule.java
  src/main/java/org/jvnet/hudson/test/junit/jupiter/JenkinsRuleExtension.java
  src/main/java/org/jvnet/hudson/test/junit/jupiter/JenkinsRuleResolver.java
  src/test/java/org/jvnet/hudson/test/junit/jupiter/JenkinsRuleResolverTest.java
  src/test/java/org/jvnet/hudson/test/junit/jupiter/JenkinsRuleResolverWithMethodScopeTest.java
Labels: enhancement

#309 Miscellaneous code cleanup
  src/main/java/org/jvnet/hudson/test/BuildWatcher.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
  src/main/java/org/jvnet/hudson/test/MemoryAssert.java
  src/main/java/org/jvnet/hudson/test/MockFolder.java
  src/main/java/org/jvnet/hudson/test/PluginAutomaticTestBuilder.java
  src/main/java/org/jvnet/hudson/test/ResponseCapturingOutput.java
  src/main/java/org/jvnet/hudson/test/WorkspaceCopyFileBuilder.java
  src/test/java/org/jvnet/hudson/main/AppTest.java
Labels: chore
