Repository jenkinsci/jenkins-test-harness, pull requests merged in 2021-04, with the labels that each got.

#293 NPE observed in RealJenkinsRule.startJenkins
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Labels: bug

#295 RealJenkinsRule.withHost
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Labels: enhancement

#297 RealJenkinsRule: wait for max 60 seconds for Jenkins to terminate
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Labels: bug

#298 Do not periodically JenkinsRule.dumpThreads when debugging
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Labels: bug

#299 Refresh JEP-229 workflow
  .github/workflows/cd.yaml
Labels: chore

#296 CLICommandInvoker was being too strict about how a CLICommand was registered
  src/main/java/hudson/cli/CLICommandInvoker.java
Labels: bug

#302 [JENKINS-65068] `RestartableJenkinsRule`: Handle `NoSuchFileException` thrown from `FileTreeWalker`
  src/main/java/org/jvnet/hudson/test/RestartableJenkinsRule.java
  src/test/java/org/jvnet/hudson/test/RestartableJenkinsRuleTest.java
Labels: bug
