Repository jenkinsci/jenkins-test-harness, pull requests merged in 2021-11, with the labels that each got.

#342 Allow environment variables to be defined on Jenkins process
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
  src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
Labels: enhancement

#347 [JENKINS-67086] Ensure a free port is used by RealJenkinsRule
  src/main/java/org/jvnet/hudson/test/IOUtil.java
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Labels: bug

#349 update documentation link in Javadoc
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: documentation

#345 Use generics where possible
  src/main/java/org/jvnet/hudson/test/ComputerConnectorTester.java
  src/main/java/org/jvnet/hudson/test/DefaultConstructorChecker.java
  src/main/java/org/jvnet/hudson/test/GroovyHudsonTestCase.java
  src/main/java/org/jvnet/hudson/test/GroovyJenkinsRule.java
  src/main/java/org/jvnet/hudson/test/JenkinsComputerConnectorTester.java
  src/main/java/org/jvnet/hudson/test/JenkinsMatchers.java
  src/main/java/org/jvnet/hudson/test/JenkinsRecipe.java
  src/main/java/org/jvnet/hudson/test/MemoryAssert.java
  src/main/java/org/jvnet/hudson/test/RestartableJenkinsRule.java
  src/main/java/org/jvnet/hudson/test/TestExtensionLoader.java
  src/main/java/org/jvnet/hudson/test/junit/FailedTest.java
  src/main/java/org/jvnet/hudson/test/recipes/Recipe.java
  src/main/java/org/jvnet/hudson/test/recipes/WithPluginManager.java
Labels: internal

#350 Remove usages of JNR
  src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
Labels: removed
