Repository jenkinsci/jenkins-test-harness, pull requests merged in 2022-03, with the labels that each got.

#391 Add missing `@Override` annotations
  src/main/java/hudson/cli/CLICommandInvoker.java
  src/main/java/hudson/slaves/DummyCloudImpl.java
  src/main/java/org/jvnet/hudson/test/CaptureEnvironmentBuilder.java
  src/main/java/org/jvnet/hudson/test/ClosureExecuterAction.java
  src/main/java/org/jvnet/hudson/test/ExtractChangeLogSet.java
  src/main/java/org/jvnet/hudson/test/FailureBuilder.java
  src/main/java/org/jvnet/hudson/test/FakeChangeLogSCM.java
  src/main/java/org/jvnet/hudson/test/GroovyHudsonTestCase.java
  src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
  src/main/java/org/jvnet/hudson/test/JellyTestSuiteBuilder.java
  src/main/java/org/jvnet/hudson/test/JenkinsMatchers.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
  src/main/java/org/jvnet/hudson/test/MockBuilder.java
  src/main/java/org/jvnet/hudson/test/MockFolder.java
  src/main/java/org/jvnet/hudson/test/PretendSlave.java
  src/main/java/org/jvnet/hudson/test/SleepBuilder.java
  src/main/java/org/jvnet/hudson/test/TemporaryDirectoryAllocator.java
  src/main/java/org/jvnet/hudson/test/TestBuilder.java
  src/main/java/org/jvnet/hudson/test/TestCrumbIssuer.java
  src/main/java/org/jvnet/hudson/test/TestNotifier.java
  src/main/java/org/jvnet/hudson/test/ThreadPoolImpl.java
  src/main/java/org/jvnet/hudson/test/UnstableBuilder.java
  src/main/java/org/jvnet/hudson/test/junit/GroupedTest.java
  src/main/java/org/jvnet/hudson/test/recipes/LocalData.java
  src/main/java/org/jvnet/hudson/test/recipes/PresetData.java
  src/main/java/org/jvnet/hudson/test/rhino/CallStackFrame.java
  src/main/java/org/jvnet/hudson/test/rhino/JavaScriptDebugger.java
Labels: skip-changelog

#390 Fix `DMI_RANDOM_USED_ONLY_ONCE` SpotBugs violation
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: skip-changelog

#399 Restore working version of `MemoryAssert#assertGC`
  pom.xml
  src/test/java/org/jvnet/hudson/test/MemoryAssertTest.java
Labels: bug

#392 Fix `DM_DEFAULT_ENCODING` SpotBugs violations
  src/main/java/hudson/cli/CLICommandInvoker.java
  src/main/java/org/jvnet/hudson/test/ExtractChangeLogParser.java
  src/main/java/org/jvnet/hudson/test/ExtractResourceWithChangesSCM.java
  src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: internal

#401 Add Java 11 to build/test matrix
  Jenkinsfile
Labels: test

#404 Forward compatibility with Java 17 Javadoc generation
  src/main/java/org/jvnet/hudson/test/TestExtension.java
Labels: skip-changelog

#403 Remove `-Dfile.encoding=UTF-8` from Surefire JVM arguments
  pom.xml
Labels: test

#405 Skip `MemoryAssertTest#heapUsage` on Java 17+ pending JENKINS-68019
  src/test/java/org/jvnet/hudson/test/MemoryAssertTest.java
Labels: test

#406 Remove obsolete workaround for SUREFIRE-1588
  pom.xml
Labels: test

#409 Clean up SpotBugs exclusions
  pom.xml
  src/spotbugs/excludesFilter.xml
Labels: chore

#407 Java 17 support for `RealJenkinsRule`
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Labels: enhancement

#402 Add Java 17 to build/test matrix
  Jenkinsfile
  pom.xml
Labels: test

#412 Added `RealJenkinsRuleTest.restart`
  src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
Labels: tests

#416 [JENKINS-67974] [JENKINS-68019] Upgrade INSANE
  pom.xml
  src/main/java/org/jvnet/hudson/test/MemoryAssert.java
  src/main/resources/netbeans/harness/modules/ext/org-netbeans-insane-hook.jar
  src/test/java/org/jvnet/hudson/test/MemoryAssertTest.java
Labels: enhancement
