Repository jenkinsci/jenkins-test-harness, pull requests merged in 2022-07, with the labels that each got.

#448 [JENKINS-41729] Allow UTF-8 property files
  src/main/java/org/jvnet/hudson/test/PropertiesTestSuite.java
Labels: enhancement

#450 `RealJenkinsRule`: Add new flavors of `then` / `runRemotely` allowing to return `Serializable` values
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
  src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
Labels: enhancement

#449 [JENKINS-68890] pick up htmlunit to use the xml api provided by the JDK
  pom.xml
Labels: bug

#452 Show log records when `RecordedMatcher` doesn't match
  src/main/java/org/jvnet/hudson/test/LoggerRule.java
  src/test/java/org/jvnet/hudson/test/LoggerRuleTest.java
Labels: bug

#454 Use Hamcrest matchers where possible
  src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
  src/test/java/org/jvnet/hudson/main/UseRecipesWithJenkinsRuleTest.java
  src/test/java/org/jvnet/hudson/test/JenkinsRuleTest.java
  src/test/java/org/jvnet/hudson/test/MemoryAssertTest.java
Labels: skip-changelog

#456 Bump baseline from 2.204 to 2.249
  RealJenkinsRuleInit/pom.xml
  pom.xml
Labels: internal

#455 Forward compatibility with Jetty 10 in `JenkinsRule`
  src/main/java/org/jvnet/hudson/test/NoListenerConfiguration.java
Labels: enhancement

#451 `RealJenkinsRule`: add ability to check if Jenkins fails to boot.
  pom.xml
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
  src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
  src/test/resources/plugins/failure.hpi
Labels: enhancement

#460 Update weekly version
  Jenkinsfile
Labels: skip-changelog

#461 [JENKINS-69044] Adapt to executable WAR changes in `JenkinsRule`
  src/main/java/org/jvnet/hudson/test/WarExploder.java
Labels: bug
