Repository jenkinsci/jenkins-test-harness, pull requests merged in 2022-08, with the labels that each got.

#465 Handle empty port to fix RealJenkinsRule flakiness
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Labels: bug

#473 Test on latest weekly
  Jenkinsfile
Labels: test

#475 Clarify new semantic of #getUrl
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Labels: bug

#477 Remove redundant `project.build.sourceEncoding` property
  pom.xml
Labels: skip-changelog

#479 Remove `junit-bom` from managed dependencies
  pom.xml
Labels: dependencies, java

#481 Update weekly version
  Jenkinsfile
Labels: test
