Repository jenkinsci/jenkins-test-harness, pull requests merged in 2022-02, with the labels that each got.

#386 Remove Digester dep from `ExtractChangeLogParser`
  src/main/java/org/jvnet/hudson/test/ExtractChangeLogParser.java
  src/main/java/org/jvnet/hudson/test/ExtractResourceWithChangesSCM.java
  src/test/java/org/jvnet/hudson/test/ExtractResourceWithChangesSCMTest.java
  src/test/resources/org/jvnet/hudson/test/ExtractResourceWithChangesSCMTest/initial.zip
  src/test/resources/org/jvnet/hudson/test/ExtractResourceWithChangesSCMTest/patch.zip
Labels: dependencies

#387 Remove usages of `StringUtils`
  src/main/java/org/jvnet/hudson/test/HudsonHomeLoader.java
  src/main/java/org/jvnet/hudson/test/PluginAutomaticTestBuilder.java
Labels: skip-changelog

#393 Remove unneeded injected test
  src/main/java/org/jvnet/hudson/test/JellyTestSuiteBuilder.java
Labels: enhancement

#394 EOL JSR 305
  src/test/java/org/jvnet/hudson/test/JenkinsRuleTest.java
Labels: skip-changelog
