Repository jenkinsci/jenkins-test-harness, pull requests merged in 2022-11, with the labels that each got.

#509 Use correct logger name in `RealJenkinsRule`
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Labels: bug

#516 Test against 2.377
  Jenkinsfile
Labels: skip-changelog

#515 Java 17 support for `SimpleCommandLauncher`
  src/main/java/org/jvnet/hudson/test/SimpleCommandLauncher.java
  src/test/java/org/jvnet/hudson/test/JenkinsRuleTest.java
Labels: bug

#517 Support of `RealJenkinsRule` in `InboundAgentRule`
  src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
Labels: enhancement

#512 `RealJenkinsRule` should not overwrite `JenkinsLocationConfiguration` if otherwise set
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
  src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
Labels: enhancement

#520 Some `InjectedTest.testPluginActive` failures neglected to identify tested plugin
  src/main/java/org/jvnet/hudson/test/PluginAutomaticTestBuilder.java
Labels: bug

#510 Accept multiple `Step`s in `then` and `runRemotely`
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
  src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
Labels: enhancement

#514 Allow `RealJenkinsRule` instances to specify a `name` & `color`
  src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
  src/main/java/org/jvnet/hudson/test/PrefixedOutputStream.java
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
  src/test/java/org/jvnet/hudson/test/PrefixedOutputStreamTest.java
Labels: enhancement

#523 Plumb through `JenkinsRule`/`RealJenkinsRule` when possible
  src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
Labels: skip-changelog

#524 Document #359
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Labels: documentation

#513 Allow `RealJenkinsRule` controllers to know `surefire.forkNumber`
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Labels: enhancement

#527 Remove unnecessary SpotBugs exclusions
  src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
  src/main/java/org/jvnet/hudson/test/JenkinsSessionRule.java
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
  src/main/java/org/jvnet/hudson/test/RestartableJenkinsRule.java
  src/spotbugs/excludesFilter.xml
Labels: skip-changelog

#528 Require Java 11 or newer
  Jenkinsfile
  pom.xml
Labels: breaking

#530 Remove logic for old Jenkins versions
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
  src/main/java/org/jvnet/hudson/test/PropertiesTestSuite.java
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
  src/main/java/org/jvnet/hudson/test/WarExploder.java
Labels: internal
