Repository jenkinsci/jenkins-test-harness, pull requests merged in 2022-09, with the labels that each got.

#486 Remove `oleg-nenashev` from `dependabot.yml`
  .github/dependabot.yml
Labels: skip-changelog

#488 RealJenkinsRule: get the full stacktrace when a remote call fails
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
  src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
Labels: enhancement

#491 Weed out flaky tests
  pom.xml
Labels: test
