Repository jenkinsci/jenkins-test-harness, pull requests merged in 2022-10, with the labels that each got.

#494 Test against 2.371
  Jenkinsfile
Labels: skip-changelog

#492 Make `JenkinsRule#after` more robust
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: bug

#489 Check for proc liveness
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Labels: bug

#495 Deprecate `NodeProvisionerRule`
  src/main/java/hudson/slaves/NodeProvisionerRule.java
Labels: internal

#493 Improve `InboundAgentRule`
  src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
Labels: enhancement

#496 Removing redundant stack trace from output
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Labels: bug

#499 Add jenkins-core to dependencyManagement to avoid pulling all stapler versions
  pom.xml
Labels: chore

#500 Exclusion is no longer needed
  pom.xml
Labels: chore

#502 Test latest weekly
  Jenkinsfile
Labels: test
