Repository jenkinsci/jenkins-test-harness, pull requests merged in 2023-07, with the labels that each got.

#621 `InboundAgentRule.Options.Builder.withLogger`
  src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: enhancement

#625 Test with latest weekly
  Jenkinsfile
Labels: test

#627 Automate updating of Jenkins weekly version
  .github/renovate.json
Labels: chore
