Repository jenkinsci/jenkins-test-harness, pull requests merged in 2023-05, with the labels that each got.

#576 Disable `startJenkins` timeout when debugging
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Labels: bug

#578 More options for `InboundAgentRule` launching
  src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
Labels: enhancement

#579 Honor `Jenkins.rootUrl` when launching `InboundAgentRule`
  src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
Labels: bug

#580 Support for boldface in `PrefixedOutputStream`
  src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
  src/main/java/org/jvnet/hudson/test/PrefixedOutputStream.java
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
  src/main/java/org/jvnet/hudson/test/TailLog.java
Labels: enhancement

#577 Wait for `InboundAgentRule` to be online as part of starting it
  pom.xml
  src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
  src/test/java/org/jvnet/hudson/test/InboundAgentRuleTest.java
Labels: enhancement

#585 Use `Class.getPackageName`
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Labels: chore

#584 Clean up `InboundAgent.Options` & `.Builder`
  src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
Labels: enhancement

#586 Omit `waitOnline` suggestion from `InboundAgentRule` Javadoc
  src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
Labels: documentation

#587 Remove deprecated `hamcrest-core` and `hamcrest-library` modules
  pom.xml
Labels: removed

#588 Replace hamcrest matchers with methods from non-deprecated packages
  src/main/java/org/jvnet/hudson/test/JenkinsMatchers.java
  src/main/java/org/jvnet/hudson/test/LoggerRule.java
  src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
  src/test/java/org/jvnet/hudson/test/RestartableJenkinsRuleTest.java
Labels: chore

#590 Support of jacoco agent in forked Jenkins instances
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Labels: enhancement

#591 Dispose of Windows read-only temporary files
  src/main/java/org/jvnet/hudson/test/TemporaryDirectoryAllocator.java
  src/test/java/org/jvnet/hudson/test/JenkinsRuleTest.java
Labels: bug

#595 Reduce usages of Guava
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: internal
