Repository jenkinsci/jenkins-test-harness, pull requests merged in 2023-12, with the labels that each got.

#690 Allow `RealJenkinsRule` to delay `JENKINS_HOME` initialization until first startup using new `prepareHomeLazily` method
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
  src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
Labels: enhancement

#695 JEP-227 update for JTH
  src/main/java/hudson/cli/CLICommandInvoker.java
  src/main/java/jenkins/benchmark/jmh/JmhBenchmarkState.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
  src/main/java/org/jvnet/hudson/test/MockQueueItemAuthenticator.java
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
  src/test/java/org/jvnet/hudson/test/MockAuthorizationStrategyTest.java
Labels: chore

#698 Let `InboundAgentRule.stop` tolerate a dead controller in `RealJenkinsRule` mode
  src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
Labels: bug

#699 Restore compatibility after JEP-227 updates
  src/main/java/org/jvnet/hudson/test/MockQueueItemAuthenticator.java
Labels: bug

#702 Do not swallow exceptions in `HtmlFormUtil`
  src/main/java/org/htmlunit/html/HtmlFormUtil.java
Labels: bug
