Repository jenkinsci/jenkins-test-harness, pull requests merged in 2023-10, with the labels that each got.

#669 Avoid strong refs from `ChannelShutdownListener`
  src/main/java/org/jvnet/hudson/test/ChannelShutdownListener.java
Labels: bug

#670 Avoid `-jnlpUrl` if running on a recent enough version of Remoting
  src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
Labels: internal

#671 `RealJenkinsRule.runRemotely` overloads taking 1–2 step args
  src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Labels: enhancement

#674 `RealJenkinsRule` overloads taking 3–4 args
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Labels: enhancement
