Repository jenkinsci/jenkins-test-harness, pull requests merged in 2023-06, with the labels that each got.

#575 `WarExploder` does not find the Jenkins WAR in the Gradle cache if its SHA-1 hash begins with a 0
  src/main/java/org/jvnet/hudson/test/WarExploder.java
Labels: bug

#598 Test latest weekly
  Jenkinsfile
Labels: test

#589 Upgrade to htmlunit 3.x
  pom.xml
  src/main/java/com/gargoylesoftware/htmlunit/WebClientUtil.java
  src/main/java/com/gargoylesoftware/htmlunit/WebResponseListener.java
  src/main/java/com/gargoylesoftware/htmlunit/html/DomNodeUtil.java
  src/main/java/com/gargoylesoftware/htmlunit/html/HtmlElementUtil.java
  src/main/java/com/gargoylesoftware/htmlunit/html/HtmlFormUtil.java
  src/main/java/hudson/security/pages/SignupPage.java
  src/main/java/org/jvnet/hudson/test/HudsonPageCreator.java
  src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
  src/main/java/org/jvnet/hudson/test/rhino/CallStackFrame.java
  src/main/java/org/jvnet/hudson/test/rhino/JavaScriptDebugger.java
  src/test/java/org/jvnet/hudson/main/UseRecipesWithJenkinsRuleTest.java
  src/test/java/org/jvnet/hudson/test/JenkinsRuleTest.java
Labels: dependencies, breaking

#599 Source files should live in a directory whose name matches their declared package
  src/main/java/org/htmlunit/README.md
  src/main/java/org/htmlunit/WebClientUtil.java
  src/main/java/org/htmlunit/WebResponseListener.java
  src/main/java/org/htmlunit/html/DomNodeUtil.java
  src/main/java/org/htmlunit/html/HtmlElementUtil.java
  src/main/java/org/htmlunit/html/HtmlFormUtil.java
Labels: internal

#602 Remove unused `SecureRandom` field
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: skip-changelog

#603 Remove usages of `org.apache.commons.io.IOUtils`
  src/main/java/org/jvnet/hudson/test/JavaNetReverseProxy.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
  src/main/java/org/jvnet/hudson/test/PropertiesTestSuite.java
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
  src/main/java/org/jvnet/hudson/test/SingleFileSCM.java
  src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
Labels: internal

#604 Stop suppressing Jetty logs which no longer exist
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: internal

#606 Revert jenkinsci/jenkins@84d49ceef2
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: internal

#608 Sort dependencies
  pom.xml
Labels: skip-changelog

#607 Improve Javadoc for `createWebClient`
  src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: documentation

#609 Use managed Hamcrest version
  pom.xml
Labels: internal

#605 Use correct key for `Request.maxFormContentSize`
  src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: bug

#610 `RealJenkinsRule` copy constructor sharing `home`
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Labels: enhancement

#611 Synchronize `CSSErrorHandler#ignore` in `HudsonTestCase` with the primary version in `JenkinsRule`
  src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
Labels: internal

#613 Improve the case where the Jenkins process stopped unexpectedly
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
  src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
Labels: bug

#614 Remove usages of Commons Lang 3
  src/main/java/jenkins/benchmark/jmh/JmhBenchmarkState.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: internal
