Repository jenkinsci/jenkins-test-harness, pull requests merged in 2024-09, with the labels that each got.

#829 [JEP-237] Add new method to RealJenkinsRule to start in FIPS mode
  pom.xml
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
  src/test/java/org/jvnet/hudson/test/RealJenkinsRuleFIPSTest.java
Labels: enhancement

#631 [JENKINS-73261] Drop support for Jetty 12 EE 8 in the test harness
  pom.xml
  src/main/java/jenkins/benchmark/jmh/JmhBenchmarkState.java
  src/main/java/org/jvnet/hudson/test/CaptureEnvironmentBuilder.java
  src/main/java/org/jvnet/hudson/test/ClosureExecuterAction.java
  src/main/java/org/jvnet/hudson/test/ComputerConnectorTester.java
  src/main/java/org/jvnet/hudson/test/CreateFileBuilder.java
  src/main/java/org/jvnet/hudson/test/FailureBuilder.java
  src/main/java/org/jvnet/hudson/test/GroovyHudsonTestCase.java
  src/main/java/org/jvnet/hudson/test/GroovyJenkinsRule.java
  src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
  src/main/java/org/jvnet/hudson/test/JavaNetReverseProxy.java
  src/main/java/org/jvnet/hudson/test/JenkinsComputerConnectorTester.java
  src/main/java/org/jvnet/hudson/test/JenkinsRecipe.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
  src/main/java/org/jvnet/hudson/test/MockBuilder.java
  src/main/java/org/jvnet/hudson/test/MockFolder.java
  src/main/java/org/jvnet/hudson/test/MockQueueItemAuthenticator.java
  src/main/java/org/jvnet/hudson/test/NoListenerConfiguration.java
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
  src/main/java/org/jvnet/hudson/test/TestCrumbIssuer.java
  src/main/java/org/jvnet/hudson/test/UnitTestSupportingPluginManager.java
  src/main/java/org/jvnet/hudson/test/UnstableBuilder.java
  src/main/java/org/jvnet/hudson/test/WorkspaceCopyFileBuilder.java
  src/main/java/org/jvnet/hudson/test/recipes/Recipe.java
  src/spotbugs/excludesFilter.xml
  src/test/java/org/jvnet/hudson/main/UseRecipesWithJenkinsRuleTest.java
  src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
Labels: removed

#834 Avoid calling `Jenkins.setNoUsageStatistics` unless necessary
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Labels: bug

#837 Try using `forkCount`
  Jenkinsfile
Labels: chore

#841 Restore compatibility with `withWar`
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
  src/main/java/org/jvnet/hudson/test/UnitTestSupportingPluginManager.java
  src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
Labels: bug

#839 Generalize catch to `SocketException`
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Labels: tests

#838 Improved use of `java.io.tmpdir`
  src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
  src/main/java/org/jvnet/hudson/test/JavaNetReverseProxy2.java
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
  src/main/java/org/jvnet/hudson/test/TemporaryDirectoryAllocator.java
  src/main/java/org/jvnet/hudson/test/UnitTestSupportingPluginManager.java
  src/main/java/org/jvnet/hudson/test/recipes/WithPluginManager.java
Labels: enhancement

#836 Do not let `TailLog.waitForCompletion` block forever
  src/main/java/org/jvnet/hudson/test/TailLog.java
Labels: bug

#835 `TailLog` to support reopened files
  src/main/java/org/jvnet/hudson/test/TailLog.java
  src/test/java/org/jvnet/hudson/test/TailLogTest.java
Labels: bug

#842 Revert `WithPluginManager` constructor behavior
  src/main/java/org/jvnet/hudson/test/recipes/WithPluginManager.java
Labels: bug

#843 `InboundAgentRule` should use a temp file for `agent.jar`
  src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
Labels: bug

#846 `doSafeExit` from `RealJenkinsRule` could hang
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
  src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
Labels: bug

#840 `RealJenkinsRule.setHome`
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Labels: enhancement

#847 Revert "Bump org.jenkins-ci:jenkins from 1.122 to 1.123"
  pom.xml
Labels: dependencies
