Repository jenkinsci/jenkins-test-harness, pull requests merged in 2024-05, with the labels that each got.

#763 Inline `ContextHandler.MAX_FORM_CONTENT_SIZE_KEY`
  src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: chore

#764 Deprecate `MIME_TYPES`
  src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
  src/test/java/org/jvnet/hudson/test/JenkinsRuleTest.java
Labels: chore

#765 Remove unnecessary workaround
  pom.xml
Labels: chore, developer

#766 Set server on `WebApplicationContext`
  src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: skip-changelog

#767 Avoid usage of `Server#getChildHandlerByClass`
  src/main/java/jenkins/benchmark/jmh/JmhBenchmarkState.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: internal

#768 Remove unused class
  src/main/java/org/jvnet/hudson/test/ResponseCapturingOutput.java
Labels: removed

#774 [JENKINS-73124] Remove `MIME_TYPES`
  src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: removed

#772 Update search function for Command palette
  src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
  src/main/java/org/jvnet/hudson/test/QueryUtils.java
Labels: enhancement
