Repository jenkinsci/jenkins-test-harness, pull requests merged in 2024-06, with the labels that each got.

#779 Update the minimum version of Jenkins used by RealJenkinsRule to prevent detached plugins being dragged in.
  RealJenkinsRuleInit/pom.xml
  RealJenkinsRuleInit/src/main/resources/index.jelly
  pom.xml
  src/main/resources/org/jvnet/hudson/test/RealJenkinsRuleInit.jpi
Labels: bug

#782 Dynamically create the RealJenkinsRuleInit plugin
  RealJenkinsRuleInit/pom.xml
  pom.xml
  src/main/java/org/jvnet/hudson/test/PluginUtils.java
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
  src/main/java/org/jvnet/hudson/test/RealJenkinsRuleInit.java
  src/main/resources/org/jvnet/hudson/test/RealJenkinsRuleInit.jpi
  src/test/java/org/jvnet/hudson/test/PluginUtilsTest.java
  src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
Labels: enhancement

#762 Upgrade Jetty from 10.0.20 to 12.0.10 (EE 8)
  .github/dependabot.yml
  pom.xml
  src/main/java/jenkins/benchmark/jmh/JmhBenchmarkState.java
  src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
  src/main/java/org/jvnet/hudson/test/JavaNetReverseProxy.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
  src/main/java/org/jvnet/hudson/test/NoListenerConfiguration.java
Labels: enhancement

#788 Delegate compression to servlet container
  src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: enhancement

#791 Backport "Bump org.jenkins-ci.main:jenkins-test-harness-htmlunit from 182.v85fe4a_4ee4f0 to 183.v9742e5ca_c784"
  pom.xml
Labels: dependencies, java, developer
