Repository jenkinsci/jenkins-test-harness, pull requests merged in 2024-10, with the labels that each got.

#856 Use 2.479 as baseline
  pom.xml
Labels: internal

#860 Deleting orphaned `index.jelly` from `RealJenkinsRuleInit`
  RealJenkinsRuleInit/src/main/resources/index.jelly
Labels: chore

#858 Offer a way to start the RealJenkinsRule instance with https only
  src/main/java/jenkins/test/https/KeyStoreManager.java
  src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
  src/main/keystore/generate_self_signed_cert.sh
  src/main/resources/https/test-cert.pem
  src/main/resources/https/test-keystore.p12
  src/src/main/resources/https/test-cert.pem
  src/src/main/resources/https/test-keystore.p12
  src/test/java/org/jvnet/hudson/test/RealJenkinsRuleHttpsTest.java
Labels: enhancement
