Repository jenkinsci/jenkins-test-harness, pull requests merged in 2024-07, with the labels that each got.

#795 Use `ProcessTree.killAll` from `InboundAgentRule`
  src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
Labels: bug

#801 Unfork EE 8 servlet API
  pom.xml
Labels: developer

#805 Backport `InboundAgentRule` updates from #795 and #802
  src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
Labels: enhancement

#806 Update Jetty from 10.0.21 to 10.0.22 on Java 11 branch
  pom.xml
Labels: enhancement

#810 Bump `org.jenkins-ci.main:jenkins-test-harness-htmlunit` from 183.v9742e5ca_c784 to 187.v1e8425eb_77c5 on Java 11 branch
  pom.xml
Labels: dependencies, java, developer
