Repository jenkinsci/jenkins-test-harness, pull requests merged in 2025-02, with the labels that each got.

#918 Add `RealJenkinsRule.run` / `.call` aliases
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Labels: enhancement

#920 Introduce `RealJenkinsRule.createSyntheticPlugin` to allow synthetic plugins to be installed dynamically and break compatibility for existing callers of `RealJenkinsRule.addSyntheticPlugin`
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
  src/test/java/org/jvnet/hudson/test/RealJenkinsRuleSyntheticPluginTest.java
Labels: breaking

#913 Revisit concurrency in `JavaNetReverseProxy2#service`
  src/main/java/org/jvnet/hudson/test/JavaNetReverseProxy2.java
Labels: bug

#927 Add an example of parameterized tests to `@WithJenkins` Javadoc
  src/main/java/org/jvnet/hudson/test/junit/jupiter/WithJenkins.java
Labels: documentation

#926 Deprecating `RestartableJenkinsRule`
  src/main/java/org/jvnet/hudson/test/JenkinsSessionRule.java
  src/main/java/org/jvnet/hudson/test/RestartableJenkinsRule.java
Labels: documentation

#924 Add support for custom prefix
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
  src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
Labels: enhancement
