Repository jenkinsci/jenkins-test-harness, pull requests merged in 2025-03, with the labels that each got.

#930 [JENKINS-75278] Upgrade Jetty 12.0.17 which restore UriCompliance.LEGACY previous behaviour
  pom.xml
  src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
Labels: bug, dependencies

#937 Websocket field on `JNLPLauncher` is deprecated
  src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
Labels: bug

#915 Support the new header
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: enhancement

#935 [JENKINS-75409] Add -noCertificateCheck and -cert option to IAR
  src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
  src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Labels: enhancement

#936 `JenkinsRule#restart` preserves the original root path
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
  src/test/java/org/jvnet/hudson/test/JenkinsRuleTest.java
  src/test/java/org/jvnet/hudson/test/junit/jupiter/JUnit5JenkinsRuleTest.java
Labels: bug

#943 Make `NoListenerConfiguration2` agnostic to EE version
  src/main/java/org/jvnet/hudson/test/NoListenerConfiguration2.java
Labels: internal

#944 Reduce usage of deprecated Jetty methods
  src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
  src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Labels: internal

#947 Simplify `JavaNetReverseProxy2`
  src/main/java/org/jvnet/hudson/test/JavaNetReverseProxy2.java
Labels: internal
